version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            TAG="circleci"
            docker build -t subgit:${TAG} .
            docker run -ti --rm --name subgit subgit:${TAG} --version
